config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :amenity_rooms
  resources :amenities
  resources :roles
  #devise_for :users
  resources :rooms

  get '/errors', to: 'errors#index'

  devise_for :users,
             :controllers => {:registrations => "my_devise/registrations"}
  
  root 'rooms#index'
end

app/models/amenity_room.rb
class AmenityRoom < ApplicationRecord
end

app/controllers/amenity_rooms_controller.rb
class AmenityRoomsController < ApplicationController
  before_action :set_amenity_room, only: [:show, :edit, :update, :destroy]

  # GET /amenity_rooms
  # GET /amenity_rooms.json
  def index
    @amenity_rooms = AmenityRoom.all
  end

  # GET /amenity_rooms/1
  # GET /amenity_rooms/1.json
  def show
  end

  # GET /amenity_rooms/new
  def new
    @amenity_room = AmenityRoom.new
  end

  # GET /amenity_rooms/1/edit
  def edit
  end

  # POST /amenity_rooms
  # POST /amenity_rooms.json
  def create
    @amenity_room = AmenityRoom.new(amenity_room_params)

    respond_to do |format|
      if @amenity_room.save
        format.html { redirect_to @amenity_room, notice: 'Amenity room was successfully created.' }
        format.json { render :show, status: :created, location: @amenity_room }
      else
        format.html { render :new }
        format.json { render json: @amenity_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amenity_rooms/1
  # PATCH/PUT /amenity_rooms/1.json
  def update
    respond_to do |format|
      if @amenity_room.update(amenity_room_params)
        format.html { redirect_to @amenity_room, notice: 'Amenity room was successfully updated.' }
        format.json { render :show, status: :ok, location: @amenity_room }
      else
        format.html { render :edit }
        format.json { render json: @amenity_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amenity_rooms/1
  # DELETE /amenity_rooms/1.json
  def destroy
    @amenity_room.destroy
    respond_to do |format|
      format.html { redirect_to amenity_rooms_url, notice: 'Amenity room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amenity_room
      @amenity_room = AmenityRoom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def amenity_room_params
      params.require(:amenity_room).permit(:room_id, :amenity_id)
    end
end

app/helpers/amenity_rooms_helper.rb
module AmenityRoomsHelper
end

app/views/amenity_rooms/_form.html.erb
<%= form_with(model: amenity_room, local: true) do |form| %>
  <% if amenity_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amenity_room.errors.count, "error") %> prohibited this amenity_room from being saved:</h2>

      <ul>
      <% amenity_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id %>
  </div>

  <div class="field">
    <%= form.label :amenity_id %>
    <%= form.number_field :amenity_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/amenity_rooms/edit.html.erb
<h1>Editing Amenity Room</h1>

<%= render 'form', amenity_room: @amenity_room %>

<%= link_to 'Show', @amenity_room %> |
<%= link_to 'Back', amenity_rooms_path %>

app/views/amenity_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amenity Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Amenity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amenity_rooms.each do |amenity_room| %>
      <tr>
        <td><%= amenity_room.room_id %></td>
        <td><%= amenity_room.amenity_id %></td>
        <td><%= link_to 'Show', amenity_room %></td>
        <td><%= link_to 'Edit', edit_amenity_room_path(amenity_room) %></td>
        <td><%= link_to 'Destroy', amenity_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amenity Room', new_amenity_room_path %>

app/views/amenity_rooms/new.html.erb
<h1>New Amenity Room</h1>

<%= render 'form', amenity_room: @amenity_room %>

<%= link_to 'Back', amenity_rooms_path %>

app/views/amenity_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @amenity_room.room_id %>
</p>

<p>
  <strong>Amenity:</strong>
  <%= @amenity_room.amenity_id %>
</p>

<%= link_to 'Edit', edit_amenity_room_path(@amenity_room) %> |
<%= link_to 'Back', amenity_rooms_path %>