config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :amenity_rooms
  resources :amenities
  resources :roles
  #devise_for :users
  resources :rooms

  get '/errors', to: 'errors#index'

  devise_for :users,
             :controllers => {:registrations => "my_devise/registrations"}
  
  root 'rooms#index'
end

app/models/amenity.rb
class Amenity < ApplicationRecord
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  before_action :set_amenity, only: [:show, :edit, :update, :destroy]

  # GET /amenities
  # GET /amenities.json
  def index
    @amenities = Amenity.all
  end

  # GET /amenities/1
  # GET /amenities/1.json
  def show
  end

  # GET /amenities/new
  def new
    @amenity = Amenity.new
  end

  # GET /amenities/1/edit
  def edit
  end

  # POST /amenities
  # POST /amenities.json
  def create
    @amenity = Amenity.new(amenity_params)

    respond_to do |format|
      if @amenity.save
        format.html { redirect_to @amenity, notice: 'Amenity was successfully created.' }
        format.json { render :show, status: :created, location: @amenity }
      else
        format.html { render :new }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amenities/1
  # PATCH/PUT /amenities/1.json
  def update
    respond_to do |format|
      if @amenity.update(amenity_params)
        format.html { redirect_to @amenity, notice: 'Amenity was successfully updated.' }
        format.json { render :show, status: :ok, location: @amenity }
      else
        format.html { render :edit }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amenities/1
  # DELETE /amenities/1.json
  def destroy
    @amenity.destroy
    respond_to do |format|
      format.html { redirect_to amenities_url, notice: 'Amenity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amenity
      @amenity = Amenity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def amenity_params
      params.require(:amenity).permit(:name, :description)
    end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/views/amenities/_form.html.erb
<%= form_with(model: amenity, local: true) do |form| %>
  <% if amenity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amenity.errors.count, "error") %> prohibited this amenity from being saved:</h2>

      <ul>
      <% amenity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/amenities/edit.html.erb
<h1>Editing Amenity</h1>

<%= render 'form', amenity: @amenity %>

<%= link_to 'Show', @amenity %> |
<%= link_to 'Back', amenities_path %>

app/views/amenities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amenities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amenities.each do |amenity| %>
      <tr>
        <td><%= amenity.name %></td>
        <td><%= amenity.description %></td>
        <td><%= link_to 'Show', amenity %></td>
        <td><%= link_to 'Edit', edit_amenity_path(amenity) %></td>
        <td><%= link_to 'Destroy', amenity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amenity', new_amenity_path %>

app/views/amenities/new.html.erb
<h1>New Amenity</h1>

<%= render 'form', amenity: @amenity %>

<%= link_to 'Back', amenities_path %>

app/views/amenities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @amenity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @amenity.description %>
</p>

<%= link_to 'Edit', edit_amenity_path(@amenity) %> |
<%= link_to 'Back', amenities_path %>