config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :amenity_rooms
  resources :amenities
  resources :roles
  #devise_for :users
  resources :rooms

  get '/errors', to: 'errors#index'

  devise_for :users,
             :controllers => {:registrations => "my_devise/registrations"}
  
  root 'rooms#index'
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :images, CoverUploaderUploader
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :user

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @hash = Gmaps4rails.build_markers(@room) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.images = params['room']['images']
    @results = Geocoder.search(@room.address+', '+City.find(@room.city_id).name);
    
    @room.latitude = @results.first.coordinates.first;
    @room.longitude = @results.first.coordinates.last;

    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save

        if User.find(current_user.id).role_id != Role.find_by(name: 'host').id

          @user = User.find(current_user.id)
          @user.role_id = Role.find_by(name: 'host').id
          if @user.save
            format.html { redirect_to @room, notice: 'Room was successfully created.' }
            format.json { render :show, status: :created, location: @room }
          else
            redirect_to errors_path
          end
        else
          format.html { redirect_to @room, notice: 'Room was successfully created.' }
          format.json { render :show, status: :created, location: @room }
        end

      else
        redirect_to errors_path
        # format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :description, :price, :rules, :address, :latitude, :longitude, :city_id, :user_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :rules %>
    <%= form.text_area :rules %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.collection_select :city_id, City.all, :id, :name, prompt: "Select City" %><span id="cityError"></span><br/><br/>

    <%#= form.number_field :city_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<% if not can? :read, Room %>

  <%= link_to 'New Room', new_room_path %>

<% end %> <br/><br/><br/><br/>
<% @rooms.each do |room| %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Rules</th>
      <th>Address</th>
      
      <th>Latitude</th>
      <th>Longitude</th>
      <th>City</th>
      <th>Edit option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <tr>
        <td><%= image_tag(room.images.url, style: 'height:250px;width:80%;max-width:800px;') if room.images %><br/></td>
        <td><%= room.name %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.rules %></td>
        <td><%= room.address %></td>
        
        <td><%= room.latitude %></td>
        <td><%= room.longitude %></td>
        <td><%= City.find(room.city_id).name %></td>
        
        <td>
          <%= link_to 'Show', room %>
         
          <%= link_to 'Edit', edit_room_path(room) %>

          <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    
  </tbody>
</table>
<% end %>
<br>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<% if user_signed_in? %>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>
<% else %>

<h1> You need to sign in inorder to host a room </h1>

<% end %>

app/views/rooms/show.html.erb
<script src="//maps.google.com/maps/api/js?key=<%ENV.fetch('API_KEY')%>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<p id="notice"><%= notice %></p>

<%= image_tag(@room.images.url, style: 'height:250px;width:80%;max-width:800px;') if @room.images %><br/>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Rules:</strong>
  <%= @room.rules %>
</p>

<p>
  <strong>Address:</strong>
  <%= @room.address %>
</p>

<p>
  <strong>City:</strong>
  <%= City.find(@room.city_id).name %>
</p>



<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

<div id='map' style="width: 800px; height: 400px"></div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>